#%RAML 0.8
title: Deployer
baseUri: "http://localhost:8080/deployer"
/deployments:
  description: Manages the deployments in the container
  get:
    displayName: getAllDeployments
    description: list all deployments
  /+{contextRoot}:
    uriParameters:
      contextRoot:
    get:
      displayName: getByContextRoot
      description: get a deployment
