FROM jboss/wildfly
ADD deployer.war /opt/jboss/wildfly/standalone/deployments/
ADD deployer.config.yaml /opt/jboss/wildfly/standalone/configuration/deployer.config.yaml
ADD deployer.root.bundle /opt/jboss/wildfly/standalone/configuration/deployer.root.bundle
