#!/usr/bin/env bash

cd $(dirname $0)

WAR=../../../target/deployer.war
TAG=wildfly-deployer

echo build WAR
cd ../../..
mvn clean package
cd -

cp ${WAR} .

docker build --tag=${TAG} .

echo ${TAG} built. run: docker run -it --rm -p 8080:8080 -p 9990:9990 --name wildfly ${TAG}
