FROM jboss/wildfly
ADD deployer.war /opt/jboss/wildfly/standalone/deployments/
ADD deployer.config.yaml /opt/jboss/wildfly/standalone/configuration/deployer.config.yaml
ADD root.deployer.config /opt/jboss/wildfly/standalone/configuration/root.deployer.config
