#repository: # TODO configure from ansible
#  type: artifactory
#  uri: http://artifactory:8081/artifactory
#  repository-snapshots: libs-snapshot-local
#  repository-releases: releases-virtual
vars:
  default.log-encoding: UTF-8
  default.group-id: {{ deployer_default_group_id }}
pin:
  loggers: [com.arjuna, org.jboss.as.config, sun.rmi, jacorb, jacorb.config, org.apache.tomcat.util.modeler]
manage: [deployables] # TODO manage all
