---
dependencies:
- t1.jee_app_server

galaxy_info:
  role_name: jee_worker
  author: t1
  description: Wildfly container running the Deployer, ready to act as a worker in a cluster
  license: Apache
  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions: [ all ]
    - name: EL
      versions: [ all ]
    - name: GenericLinux
      versions: [ all ]

  galaxy_tags:
    - jee
    - javaee
    - jakartaee
    - appserver
    - java
    - deployer
    - kubee
